# https://github.com/gustwindy/guhw-bwaa-skin
[General]

Name: z~◊《 Bwaa 》~《 guhws skin 》~ ◊~z
Author: guhw
Version: 2.7
CursorRotate: 0
CursorExpand: 0
CursorCentre: 1
CursorTrailRotate: 0

SliderStyle: 2
SliderBallFlip: 0
SliderBallFrames: 1

HitCircleOverlayAboveNumber: 1
SpinnerFadePlayfield: 0
AllowSliderBallTint: 0
AnimationFramrate: 24
//SliderBallFrames: 4

[Colours]
Combo1: 225,225,225
Combo2: 225,225,225
Combo3: 225,225,225
Combo4: 225,225,225
Combo5: 225,225,225
Combo6: 225,225,225

//Combo1: 255,255,255
//Combo2: 255,255,255

//Combo1: 64,128,255
//Combo2: 64,255,255

//Combo3: 159,64,255
//Combo4: 255,64,207

SongSelectActiveText: 255,255,255
InputOverlayText: 255,255,255

SliderBorder: 0,0,0
SliderTrackOverride: 0,0,0
MenuGlow: 255,255,255

[Fonts]

HitCirclePrefix: default
HitCircleOverlap: 160
ScorePrefix: scoreentry
ComboPrefix: scoreentry
ScoreOverlap: 4
ComboOverlap: 4